---
media_role: false
media_owner: cees
media_group: cees
media_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - nfs-common
  - pipx
  - podman
  - python3
  - python3-pip
  - rsync
  - tmux
  - vim-nox
