---
- name: Create media01 VM
  hosts: media02.griend.dev
  become: true
  gather_facts: true

  vars:
    ansible_authorized_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIARZzMKZ4lIEdk5Qd7SEl9FuMNOv1t1LExbtHg6HeBKF ansible@griend.dev'
    network_ipv4_interface: ens18
    network_static_address: '192.168.2.131'
    network_gateway_address: '192.168.2.254'

  roles:
    - griend.proxmox.network
    - griend.proxmox.ansible
    - griend.proxmox.wireguard

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
          - nfs-common
          - pipx
          - podman
          - python3
          - python3-pip
          - rsync
          - tmux
          - vim-nox
        state: present
