---
- name: Create backup01 VM
  hosts: backup01.griend.dev
  become: true
  gather_facts: true

  vars:
    ansible_authorized_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIARZzMKZ4lIEdk5Qd7SEl9FuMNOv1t1LExbtHg6HeBKF ansible@griend.dev'
    network_ipv4_interface: ens18
    network_static_address: '192.168.2.131'
    network_gateway_address: '192.168.2.254'

  roles:
    - griend.proxmox.network
    - griend.proxmox.ansible

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
          - htop
          - rsync
          - tmux
          - vim-nox
        state: present

    - name: Info btrfs filesystems
      community.general.btrfs_info:
      register: my_btrfs_info

    - ansible.builtin.debug:
        var: my_btrfs_info

    - name: Create a @snapshot subvolume under /home
      community.general.btrfs_subvolume:
        name: /@snapshot
        filesystem_device: /dev/sdb1
        state: present

    - name: Create a initial snapshot of /home
      community.general.btrfs_subvolume:
        name: /@snapshot/initial
        snapshot_source: /
        filesystem_device: /dev/sdb1
        state: present

    - name: Create a daily snapshot of /home
      community.general.btrfs_subvolume:
        name: '/@snapshot/{{ ansible_date_time.date }}'
        snapshot_source: /
        filesystem_device: /dev/sdb1
        state: present
