---
- name: Configure git01 VM
  hosts: git01.griend.dev
  become: true
  gather_facts: true

  vars:
    network_static_address: '192.168.2.134'

  roles:
    - griend.proxmox.network
    - griend.proxmox.ansible
