---
- name: Upgrade playbook
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Apt upgate
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        autoclean: true

    - name: Check for reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: required

    - name: Reboot
      ansible.builtin.reboot:
      when: required.stat.exists

