namespace: griend
name: proxmox
version: 1.0.0
readme: README.md
authors:
  - Cees van de Griend <cees@griend.dev>

description: Playground for ansible collections.

license:
  - EUPL-1.2

tags: [linux]

dependencies:
  ansible.posix: ">=1.6.2"

repository: https://gitlab.com/homelab-griend.dev/homelab-proxmox.git
documentation: https://gitlab.com/homelab-griend.dev/homelab-proxmox.git
homepage: https://gitlab.com/homelab-griend.dev/homelab-proxmox.git
issues: https://gitlab.com/homelab-griend.dev/homelab-proxmox/-/issues

build_ignore: []
