---
- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname_short }}'

- name: Set /etc/hostname
  ansible.builtin.copy:
    content: '{{ inventory_hostname_short }}'
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Disable proxy in /etc/apt/apt.conf
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf
    regexp: 'Ë†Acquire::http::Proxy .*;$'
    state: absent

- name: Create /etc/apt/apt.conf.d/50proxy
  ansible.builtin.template:
    src: 50proxy.j2
    dest: /etc/apt/apt.conf.d/50proxy
    owner: root
    group: root
    mode: '0644'

- name: Create /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

# TODO: fix interface name (ens18)
- name: Create /etc/network/interface
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Create /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Create /etc/apt/sources.list
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
