---
- name: Install Jellyfin requirements
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
      - nfs-common
    state: present

- name: Install Jellyfin GPG key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    state: present

- name: Install Jellyfin repository
  ansible.builtin.apt_repository:
    repo: 'deb https://repo.jellyfin.org/debian/ {{ ansible_distribution_release }} main'
    filename: jellyfin
    state: present

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present
    update_cache: true

#
# Check if mount point exists before trying to create it,
# else it gives an error when the mount point exists and
# is mounted read-only.
#
- name: Check if media mount point exists
  ansible.builtin.stat:
    path: /mnt/media
  register: media

- name: Create media mount point
  ansible.builtin.file:
    path: /mnt/media
    state: directory
    owner: jellyfin
    group: jellyfin
    mode: '0755'
  when: not media.stat.isdir is defined or not media.stat.isdir

- name: Copy mnt-media.mount
  ansible.builtin.copy:
    src: mnt-media.mount
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Copy mnt-media.automount
  ansible.builtin.copy:
    src: mnt-media.automount
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Start mnt-media.automount
  ansible.builtin.systemd:
    name: mnt-media.automount
    state: started
    enabled: true
    daemon-reload: true
