---
- name: Install packages
  ansible.builtin.apt:
    name: '{{ workstation_packages }}'
    state: present
  when: workstation_role

- name: Check if media mount point exists
  ansible.builtin.stat:
    path: /mnt/media
  register: media
  when: workstation_role

- name: Create media mount point
  ansible.builtin.file:
    path: /mnt/media
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: workstation_role and (not media.stat.isdir is defined or not media.stat.isdir)

- name: Copy mnt-media.mount
  ansible.builtin.copy:
    src: mnt-media.mount
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'
  when: workstation_role

- name: Copy mnt-media.automount
  ansible.builtin.copy:
    src: mnt-media.automount
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'
  when: workstation_role

- name: Start mnt-media.automount
  ansible.builtin.systemd:
    name: mnt-media.automount
    state: started
    enabled: true
    daemon-reload: true
  when: workstation_role

- name: Signal GPG key
  ansible.builtin.apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present
  when: workstation_install_signal

- name: Signal Repository 
  ansible.builtin.apt_repository:
    repo: 'deb https://updates.signal.org/desktop/apt xenial main'
    state: present
  when: workstation_install_signal

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    state: present
  when: workstation_install_signal
