---
- name: Synchronize localhost to backup01 playbook
  hosts: localhost

  tasks:
    - name: Synchronize to backup01 task
      ansible.posix.synchronize:
        src: /home/cees/Documents/
        dest: backup01.griend.dev:/srv/backup/Documents

    - name: Synchronize to nas01 task
      ansible.posix.synchronize:
        src: /home/cees/Documents/
        dest: nas01.griend.dev:/mnt/pool0/Home/cees/Documenten
