---
- name: Download rclone
  ansible.builtin.get_url:
    url: "{{ backup_rclone_url }}"
    dest: /opt/download/rclone-linux-amd64.deb
    owner: root
    group: root
    mode: '0644'
  when: backup_role

- name: Install rclone
  ansible.builtin.apt:
    deb: /opt/download/rclone-linux-amd64.deb
    state: present
  when: backup_role
