---
- name: Pull remote github repositories
  hosts: git01.griend.dev
  become: yes
  become_user: cees
  gather_facts: false

  tasks:
    - name: Create destinations
      ansible.builtin.file:
        name: '/srv/{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - cvdg
        - griend

    - name: Pull repositories cvdg
      ansible.builtin.git:
        repo: 'https://github.com/cvdg/{{ item }}'
        dest: '/srv/cvdg/{{ item }}'
      with_items:
        - cvdg
        - cvdg.github.io
        - dotfiles
        - gezondheid
        - homelab
        - notes

    - name: Pull repositories griend
      ansible.builtin.git:
        repo: 'https://github.com/griend/{{ item }}'
        dest: '/srv/griend/{{ item }}'
      with_items:
        - griend.github.io
        - sksc
