---
- name: Create /opt/download
  ansible.builtin.file:
    dest: /opt/download
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download neovim
  ansible.builtin.get_url:
    url: '{{ nvim_url }}'
    dest: /opt/download/nvim-linux64.tar.gz
    checksum: '{{ nvim_checksum }}'
    owner: root
    group: root
    mode: '0644'

- name: Extract neovim
  ansible.builtin.unarchive:
    src: /opt/download/nvim-linux64.tar.gz
    remote_src: true
    dest: /opt
    owner: root
    group: root
    mode: '0755'
