---
- name: Add proxmox GPG key
  ansible.builtin.apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg

- name: Add proxmox repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription

- name: Update apt cache
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600

- name: Install proxmox-ve kernel
  ansible.builtin.apt:
    name: proxmox-default-kernel
    state: present

- name: Reboot
  ansible.builtin.reboot:

- name: Install proxmox-ve packages
  ansible.builtin.apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
      - chrony
    state: present
