---
- name: Disable Proxmox VE Enterprise Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    backrefs: true
    regexp: '^deb (.*) pve-enterprise'
    line: '# deb \1 pve-enterprise'
  when: ansible_hostname.startswith('pve')

- name: Disable Proxmox VE Enterprise Ceph Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    backrefs: true
    regexp: '^deb (.*) enterprise'
    line: '# deb \1 enterprise'
  when: ansible_hostname.startswith('pve')

- name: Enable Proxmox VE No-Subscription Repository
  ansible.builtin.apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    filename: pve-install-repo.list
    state: present
  when: ansible_hostname.startswith('pve')
