---
services:
  qbittorrent:
    image: docker.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PODMAN_USERNS="keep-id:uid=1000:1000,gid=1000:1000"
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=9080
      - TORRENTING_PORT=6881
    ports:
      - 9080:9080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./appdata/qbittorrent:/config
      - /data/torrent:/data/torrent
    restart: unless-stopped
  
  prowlarr:
    container_name: prowlarr
    image: docker.io/linuxserver/prowlarr:latest
    environment:
      - PODMAN_USERNS="keep-id:uid=1000:1000,gid=1000:1000"
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: docker.io/linuxserver/sonarr:latest
    environment:
      - PODMAN_USERNS="keep-id:uid=1000:1000,gid=1000:1000"
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: docker.io/linuxserver/radarr:latest
    environment:
      - PODMAN_USERNS="keep-id:uid=1000:1000,gid=1000:1000"
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./appdata/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
