---
- name: Create backup01 VM
  hosts: backup01.griend.dev
  become: true
  gather_facts: true

  tasks:
    - name: Info btrfs filesystems
      community.general.btrfs_info:
      register: my_btrfs_info

    - ansible.builtin.debug:
        var: my_btrfs_info

    - name: Create a @snapshot subvolume under /home
      community.general.btrfs_subvolume:
        name: /@snapshot
        filesystem_device: /dev/sdb1
        state: present

    - name: Create a initial snapshot of /home
      community.general.btrfs_subvolume:
        name: /@snapshot/initial
        snapshot_source: /
        filesystem_device: /dev/sdb1
        state: present

    - name: Create a daily snapshot of /home
      community.general.btrfs_subvolume:
        name: '/@snapshot/{{ ansible_date_time.date }}'
        snapshot_source: /
        filesystem_device: /dev/sdb1
        state: present
