---
- name: Fetch ssh_host_keys playbook
  hosts: all
  become: true
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true

  tasks:
    - name: Set download directory
      ansible.builtin.set_fact:
        ssh_host_keys_download_dir: '{{ playbook_dir }}/../roles/ssh_host_keys/files/{{ inventory_hostname }}'

    - name: Fetch ssh_host_keys
      ansible.builtin.fetch:
        src: '{{ item }}'
        dest: '{{ ssh_host_keys_download_dir }}/{{ item | basename }}'
        flat: true
      with_fileglob:
        - '/etc/ssh/ssh_host_*'
      register: fetched

    - name: Todo encrypt
      ansible.builtin.debug:
        var: fetched
