---
- name: Install requirements
  ansible.builtin.apt:
    name: '{{ nvim_requirements }}'
    state: present

- name: Create /opt/download
  ansible.builtin.file:
    dest: /opt/download
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download neovim
  ansible.builtin.get_url:
    url: '{{ nvim_url }}'
    dest: /opt/download/nvim-linux64.tar.gz
    checksum: '{{ nvim_checksum }}'
    owner: root
    group: root
    mode: '0644'

- name: Extract neovim
  ansible.builtin.unarchive:
    src: /opt/download/nvim-linux64.tar.gz
    remote_src: true
    dest: /opt
    owner: root
    group: root
    mode: '0755'

- name: Download lazygit
  ansible.builtin.get_url:
    url: '{{ lazygit_url }}'
    dest: '/opt/download/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz'
    owner: root
    group: root
    mode: '0644'

- name: Extract lazygit
  ansible.builtin.unarchive:
    src: '/opt/download/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz'
    remote_src: true
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
