---
- name: Install packages
  ansible.builtin.apt:
    name:
      - resolvconf
      - wireguard
    state: present
  when: wireguard_role

- name: Create /etc/wireguard/wg0.conf
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  when: wireguard_role

- name: Create wg-quick@wg0.service
  ansible.builtin.systemd:
    name: wg-quick@wg0.service
    state: started
    enabled: true
    daemon_reload: true
  when: wireguard_role
